---

- git:
    repo: '{{ repo }}'
    dest: '{{ basedir }}'
  tags: git
  name: get isync src

- apt:
    name: '{{ item }}'
  with_items: '{{ deps }}'
  become: True
  tags: apt
  name: install build tools

- with_nested: [ '{{ commands }}' ]
  loop_control: { label: '{{ item[0] }}' }
  become: '{{ item[3] }}'
  command: '{{ item[1] }}'
  args:
    chdir: '{{ basedir }}'
    creates: '{{ item[2] }}'
  tags: install
  name: configure compile and install isync

- template:
    src: mbsyncrc.j2
    dest: ~/.mbsyncrc
    backup: True
  tags: config
  name: generate isync user config

- file:
    path: '{{ item.maildir }}/{{ item.id }}'
    state: directory
  with_items: '{{ accounts }}'
  loop_control: { label: '{{ item.id }}' }
  tags: dirs
  name: crate user config induced dirs

- apt:
    name: maildir-utils
  become: True
  tags: mu
  name: install mu for indexing
